services:
  mqtt:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"

  hass:
    image: ghcr.io/home-assistant/home-assistant:stable
    # volumes:
    #   - ./hass-config/:/config
    ports:
      - "8123:8123"

  app:
    image: ghcr.io/go4ble/my-propane-mqtt:0.1.0-SNAPSHOT
    environment:
      MQTT_HOST: mqtt
      MY_PROPANE_USER_POOL_ID: ""
      MY_PROPANE_CLIENT_ID: ""
      MY_PROPANE_CLIENT_SECRET: ""
      MY_PROPANE_PASSWORD: ""
      MY_PROPANE_USERNAME: ""
